spring:
  application:
    name: config-server
  cloud:
    config:
    server:
      git:
       uri: https://github.com/Cihan-KARA-hub/cursor-microservices.git
       default-label: main
        profile: dev
       search-paths: 
         - config/
         - config/{application}
                    
server:
  port:8787